#include <stdio.h>
#include <iostream>
#include <sstream>
#include "login.cpp"
#include "create.cpp"
#include "llamaDelete.cpp"
#include "buy.cpp"
#include "sell.cpp"
#include "refund.cpp"
#include "logout.cpp"